

spring.application.name=backend


#BD
spring.datasource.url=jdbc:postgresql://localhost:5432/project_management_ai
spring.datasource.username=abdo
spring.datasource.password=abdo
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

#jpa
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

#jwt
jwt.secret=cHJvamV4aWEtc2VjcmV0LWtleS1zdXBlci1sb25ndWUtbWluaW11bS0zMi1jaGFycy0yMDI0IQ==
jwt.expiration=86400000



#jms
spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin
spring.jms.pub-sub-domain=false

#gemini
gemini.api.key=${GEMINI_API_KEY:test-key}
gemini.model=gemini-1.5-flash
gemini.timeout=30

#pagination
spring.data.web.pageable.default-page-size=20
spring.data.web.pageable.max-page-size=100


# RESILIENCE4J ? CIRCUIT BREAKER

resilience4j.circuitbreaker.instances.geminiService.sliding-window-size=10
resilience4j.circuitbreaker.instances.geminiService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.geminiService.wait-duration-in-open-state=30s
resilience4j.circuitbreaker.instances.geminiService.register-health-indicator=true
resilience4j.retry.instances.geminiService.max-attempts=3
resilience4j.retry.instances.geminiService.wait-duration=2s
resilience4j.timelimiter.instances.geminiService.timeout-duration=30s

#openapi / swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html


# ACTUATOR

management.endpoints.web.exposure.include=health,info,metrics,circuitbreakers
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true


server.port=8080