spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/project_management_ai
spring.datasource.username=abdo
spring.datasource.password=abdo
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080